#num1 = int('1234')
#num2 = int('4321')
#print(num1 + num2)
#num3 = int('123')
#num4 = int('2!')
#print(num3 + num4)
#num5 = int('3')
#num6 = int('2.5')
#print(num5 - num6)
#num7 = int(1.5)
#num8 = int(6)
#print(num7 + num8)
#num9 = float('-0.5')
#num0 = float('6')
#print(num9 + num0)
#num10 = float('2.0')
#num11 = float('5 + 5')
#print(num10 - num11)
#num12 = float(3.0)
#num13 = float(2 - 2)
#print(num12 * num13)
#print(25_000)
#print(25_000 == 25000)
#kat1 = input(float())
#kat2 = input(float())
#S1 = kat1 * kat2 * 0.5
#print(S1)
#numb = int(input())
#C = float(5 / 9)
#F = float(9 / 5)
#temp =  F * (numb - 32)
#if temp ==  C * (numb - 32):
#print(temp)
#else:
#print(F * numb + 32)
#numbe = float(input())
#ans = (int(numbe*10)%10)
#print(ans)
# abs -- chislo v module. max -- max number min -- minimal number
#number = max(1, 3, -5, 7) + min(1, 3, -5, 7) + abs(-17)
#print(number)
#numb1 = int(input())
#numb2 = int(input())
#numb3 = int(input())
#maxnum = max(numb3, numb2, numb1)
#minnum = min(numb3, numb2, numb1)
#centre = (numb3 + numb2 + numb1) - maxnum - minnum
#print(maxnum, centre, minnum)
#a1 = float(input())
#a2 = float(input())
#a3 = float(input())
#a4 = float(input())
#a5 = float(input())
#print(abs(a1) + abs(a2) + abs(a3) + abs(a4) + abs(a5))
# str -- from number to stroke (text)
# len -- count every single symbol in text INCLUDING SPACES
#str1 = '1'
#str2 = str1 + '2' + str1
#str3 = str2 + '3' + str2
#str4 = str3 + '4' + str3
#print(str4)
#team = input()
#letters = len(team)
#print('Football team', team, 'lasts for', letters, 'letters' )
#city = input()
#city1 = input()
#city2 = input()
#x = len(city)
#y = len(city1)
#z = len(city2)
#if z < x < y and y < x < z
#print(min(x, y, z)) and print(max(x, y, z))
